// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountPoolSummaryResponse = { totalAccounts: number, activeLeases: number, availableAccounts: number | null, leasedAccounts: number | null, pausedAccounts: number | null, drainingAccounts: number | null, nearExhaustedAccounts: number | null, exhaustedAccounts: number | null, errorAccounts: number | null, };
