// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountPoolPolicyResponse = { allocationMode: string, allowContextReuse: boolean, proactiveSwitchThresholdPercent: number | null, minSwitchIntervalSecs: bigint | null, };
