// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPoolDiagnosticsSeverity } from "./AccountPoolDiagnosticsSeverity";
import type { AccountPoolReasonCode } from "./AccountPoolReasonCode";

export type AccountPoolDiagnosticsIssueResponse = { severity: AccountPoolDiagnosticsSeverity, reasonCode: AccountPoolReasonCode, message: string, accountId: string | null, holderInstanceId: string | null, nextRelevantAt: bigint | null, };
