// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountLeaseUpdatedNotification = { accountId: string | null, poolId: string | null, suppressed: boolean, leaseAcquiredAt: number | null, minSwitchIntervalSecs: number | null, proactiveSwitchPending: boolean | null, proactiveSwitchSuppressed: boolean | null, proactiveSwitchAllowedAt: number | null, };
