// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountOperationalState } from "./AccountOperationalState";

export type AccountPoolAccountsListParams = { poolId: string, accountId?: string | null, cursor?: string | null, limit?: number | null, states?: Array<AccountOperationalState> | null, accountKinds?: Array<string> | null, };
