// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountOperationalState } from "./AccountOperationalState";
import type { AccountPoolLeaseResponse } from "./AccountPoolLeaseResponse";
import type { AccountPoolQuotaResponse } from "./AccountPoolQuotaResponse";
import type { AccountPoolReasonCode } from "./AccountPoolReasonCode";
import type { AccountPoolSelectionResponse } from "./AccountPoolSelectionResponse";

export type AccountPoolAccountResponse = { accountId: string, backendAccountRef: string | null, accountKind: string, enabled: boolean, healthState: string | null, operationalState: AccountOperationalState | null, allocatable: boolean | null, statusReasonCode: AccountPoolReasonCode | null, statusMessage: string | null, currentLease: AccountPoolLeaseResponse | null, quota: AccountPoolQuotaResponse | null, selection: AccountPoolSelectionResponse | null, updatedAt: bigint, };
