// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPoolQuotaWindowResponse } from "./AccountPoolQuotaWindowResponse";

export type AccountPoolQuotaFamilyResponse = { limitId: string, primary: AccountPoolQuotaWindowResponse, secondary: AccountPoolQuotaWindowResponse, exhaustedWindows: string, predictedBlockedUntil: bigint | null, nextProbeAfter: bigint | null, observedAt: bigint, };
