// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountStartupCandidatePool } from "./AccountStartupCandidatePool";
import type { AccountStartupResolutionIssueSource } from "./AccountStartupResolutionIssueSource";
import type { AccountStartupResolutionIssueType } from "./AccountStartupResolutionIssueType";

export type AccountStartupResolutionIssue = { type: AccountStartupResolutionIssueType, source: AccountStartupResolutionIssueSource, poolId: string | null, candidatePoolCount: number | null, candidatePools: Array<AccountStartupCandidatePool> | null, message: string | null, };
