// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPoolEventType } from "./AccountPoolEventType";

export type AccountPoolEventsListParams = { poolId: string, accountId?: string | null, types?: Array<AccountPoolEventType> | null, cursor?: string | null, limit?: number | null, };
