// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountStartupAvailability } from "./AccountStartupAvailability";
import type { AccountStartupResolutionIssue } from "./AccountStartupResolutionIssue";

export type AccountStartupSnapshot = { effectivePoolId: string | null, effectivePoolResolutionSource: string, configuredDefaultPoolId: string | null, persistedDefaultPoolId: string | null, startupAvailability: AccountStartupAvailability, startupResolutionIssue: AccountStartupResolutionIssue | null, selectionEligibility: string, };
