// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountPoolReasonCode = "durablySuppressed" | "missingPool" | "preferredAccountSelected" | "automaticAccountSelected" | "preferredAccountMissing" | "preferredAccountInOtherPool" | "preferredAccountDisabled" | "preferredAccountUnhealthy" | "preferredAccountBusy" | "manualPause" | "manualDrain" | "quotaNearExhausted" | "quotaExhausted" | "authFailure" | "cooldownActive" | "minimumSwitchInterval" | "noEligibleAccount" | "leaseHeldByAnotherInstance" | "nonReplayableTurn" | "unknown";
