// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPoolBackendKind } from "./AccountPoolBackendKind";
import type { AccountPoolPolicyResponse } from "./AccountPoolPolicyResponse";
import type { AccountPoolSummaryResponse } from "./AccountPoolSummaryResponse";

export type AccountPoolReadResponse = { poolId: string, backend: AccountPoolBackendKind, summary: AccountPoolSummaryResponse, policy: AccountPoolPolicyResponse, refreshedAt: bigint, };
