// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountLeaseReadResponse = { active: boolean, suppressed: boolean, accountId: string | null, poolId: string | null, leaseId: string | null, leaseEpoch: number | null, healthState: string | null, switchReason: string | null, suppressionReason: string | null, transportResetGeneration: number | null, lastRemoteContextResetTurnId: string | null, nextEligibleAt: number | null, effectivePoolResolutionSource: string | null, configuredDefaultPoolId: string | null, persistedDefaultPoolId: string | null, };
