// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { AccountPoolEventType } from "./AccountPoolEventType";
import type { AccountPoolReasonCode } from "./AccountPoolReasonCode";

export type AccountPoolEventResponse = { eventId: string, occurredAt: bigint, poolId: string, accountId: string | null, leaseId: string | null, holderInstanceId: string | null, eventType: AccountPoolEventType, reasonCode: AccountPoolReasonCode | null, message: string, details: JsonValue | null, };
