// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPoolDiagnosticsIssueResponse } from "./AccountPoolDiagnosticsIssueResponse";
import type { AccountPoolDiagnosticsStatus } from "./AccountPoolDiagnosticsStatus";

export type AccountPoolDiagnosticsReadResponse = { poolId: string, generatedAt: bigint, status: AccountPoolDiagnosticsStatus, issues: Array<AccountPoolDiagnosticsIssueResponse>, };
